### ISSUE TITLE
Creating a channel with Python

### ISSUE THREAD

**Issue by aswanevelder** [jembi/openhim-core-js#1024]
I am unable to authenticate the token, any advice will be greatly appreciated. Printing the output from the GET /channels, I get an Unauthorized.

```
import sys, json, requests, hashlib

r = requests.get('https://localhost:8082/authenticate/root@openhim.org', verify=False)
openauth = r.json()
print(openauth)

j = json.dumps(openauth)
salt = json.loads(j)["salt"]
print(salt)
ts = json.loads(j)["ts"]
print(ts)

passwordhash = hashlib.sha512(str(salt+'openhim-password').encode('utf-8'))
print(passwordhash.hexdigest())

authtoken = hashlib.sha512(str(passwordhash.hexdigest()+salt+ts).encode('utf-8'))
print(authtoken.hexdigest())

url = 'https://localhost:8082/channels'
params = {'auth-username':'root@openhim.org','auth-ts':ts,'auth-salt':salt,'auth-token':authtoken.hexdigest()}
chn = requests.get(url, params=params, verify=False)
print(chn.text)

```

**Comment by BMartinos** [comment]
Hi @aswanevelder 

Are you able to authenticate to the API on any of the other endpoints or is this endpoint the only one giving this authentication issue? 

Are you running the core manually, or using the docker container? and which version

**Comment by aswanevelder** [comment]
Hi Martin,

I just tried the GET on channels. Trying to automate a channel create to Hearth. The environment runs in Kubernetes in AWS EKS at the moment. 

I do believe my authentication logic is flawed.

**Comment by BMartinos** [comment]
Hi @aswanevelder 

It seems that you arent generating your auth-token correctly. This could also be due to the server timestamp difference that is invalidating the token. 

Have a look at how we currently do if from the console side of things
https://github.com/jembi/openhim-console/blob/master/app/scripts/services/authinterceptor.js#L18-L43
