### ISSUE TITLE
openhim-dev.transactions takes up a lot of space

### ISSUE THREAD

**Issue by euanmillar** [jembi/openhim-core-js#1167]
Hello Jembi friends!

Recently I have been testing backing up OpenHIM from a server that had a lot of data and restoring it onto a new cluster.  
When I was restoring, I noticed that the openhim-dev.transactions collection had grown to take up **26.4GB**

I looked in the docs to see if there is a way I can configure openhim-dev.transactions to take up less space or rotate occasionally but I couldn't find anything.  

Is there a config setting I can use to keep the size of this collection at a reasonable limit?

Many thanks,

Euan

**Comment by rcrichton** [comment]
Hey Euan, in the channel config in the OpenHIM console there are option that allow you to set the retention period for transaction bodies. That should help a lot.

**Comment by euanmillar** [comment]
Thanks Ryan!

**Comment by euanmillar** [comment]
Hey Ryan! @rcrichton 

I hope you are all doing well.

We have used maxBodyAgeDays in all our channels for some time now set to 30 days, but OpenHIM is still far and away the largest database collection we have in our stack.  I'm not sure that this prop works at the moment.  I am looking at a recent deployment and I have OpenHIM logs for all channels stretching back further than 30 days.  I think this is a bug that needs reopening.  Our version of OpenHIM is docker image: jembi/openhim-core:7

What do you think?

**Comment by rcrichton** [comment]
Hi, sorry for the delay. This setting only removed the transaction body which is the largest part of transactions. It should be correctly removing transaction bodies. Are you still seeing these stick around? You should still be able to see the transactions in the transaction log, just with no bodies attached.
