### ISSUE TITLE
auto retry transactions continues even after deletion from collections and correct channel configurations 

### ISSUE THREAD

**Issue by ccwhite333** [jembi/openhim-core-js#1185]
I have about 800 transactions that got sent in batch from another system, those transactions failed, and even though the settings for the channel were set to disable auto retry, they were sent for retry.

So now i am having about 900 transactions attempted to retry every minute

In order to get this to stop I:

1) deleted all documents from the autoretries collection
2) set all autoretry to false in the transactions collection
3) restarted openhim-core

I am still seeing hundreds of transactions being attempted and i don't know how to stop it

please HELP!

Also - why is it autoretrying if i have the channel settings set to autoretry: false?

**Comment by nour-borgi** [comment]
Hi @ccwhite333, did you try to set it to true and set the max attempts to 1 ? 
Also can you check if there are any running tasks ?

**Comment by ccwhite333** [comment]
I deleted all tasks from the mongo db though they were all marked complete.

I have replaced the settings. do i need to restart openhim-console?

**Comment by nour-borgi** [comment]
I m not sure if the restart of openhim-console is going to help with anything, but you can do that.
Are you still seeing new retry-transactions ?

**Comment by job-isabai** [comment]
Do we have a solution to this issue.
My OpenHIM setup is retrying almost 30 transactions after every 5 minutes. Kindly help

**Comment by nour-borgi** [comment]
Could you provide us with more context to be able to understand the situation please?
Like: 
- A screenshot of the Openhim Transaction logs, and if it is confidential, you can just show us this part to know which type of rerun you're facing
![image](https://user-images.githubusercontent.com/48720958/236409528-25b4ea11-f674-48b5-a00a-8db6181c0d85.png)
- A screenshot of the Tasks UI
- Also is it happening with one channel or multiple channels ? maybe you can provide us with the current config of that channel ? 
- Are the retrying transaction failing ? 

Also, could you check the below: 
- Are you sure you don't have any external system that triggering these transactions ? 
- Could you try to remove all the current tasks (or pause them) and disable all the auto-retries on all the channels in the UI? 

Thanks.

**Comment by job-isabai** [comment]
Hello @nour-borgi ,
OpenHIM retries all failed and completed transaction until they are successful.
Here is the screenshot of Transaction page:
![image](https://user-images.githubusercontent.com/100341653/236419350-842be318-c030-403c-a48a-11d4d0a90e8c.png)
I went to the task-ui and pause/canceled all the transactions just to stop the retries but it did not work. here is a screenshot
![image](https://user-images.githubusercontent.com/100341653/236419817-758b7491-5215-4fbc-a3bf-0333f40abc09.png)
I have set no-retry on all channels but this behavior is on all the channels, it only stops when transactions are marked successful.

**Comment by nour-borgi** [comment]
Are you sure not the external system is the one sending requests till it succeeds ?

it seems that the transactions coming do not have any of these icons: 
![image](https://user-images.githubusercontent.com/48720958/236425144-d36e1dd4-8da1-479c-a149-528d5277c9ab.png)

Actually if you can see one of these icons you could hover over them and it will explain it. So for rerun transactions there will be a single arrow in a circle for a transaction that is the child transaction (the actual rerun) then there will be two arrows in a circle. 

In the DB you can check the wasRerun property on a transaction or the parentID or childIDs properties for the relationship between parent and child transaction (the child is the rerun).

**Comment by job-isabai** [comment]
Thank you, this makes sense, Let me check.
Do we have web_interface for the Mongodb running on OpenHIM.

**Comment by nour-borgi** [comment]
nope we don't but you can access the mongo container and display content using docker command: `docker exec -it <container_name> bash`

and then you can use mongo commands to display data
