### ISSUE TITLE
Fix response sent from one openhim to another openhim instance

### ISSUE THREAD

**Issue by reagan-meant** [jembi/openhim-core-js#1229]
When one uses one openhim(A) to connect to another openhim instance(B)
Instance B is on the same server with other services like opencr and SHR
The issue is that the response from opencr or hapi fhir server is legible in the openhim(B) but the response sent to openhim(A)  is illegible

**Comment by rcrichton** [comment]
HI, do you perhaps have a screenshot you can share with what it looks like?

**Comment by reagan-meant** [comment]
Postman Request
<img width="875" alt="postman" src="https://github.com/jembi/openhim-core-js/assets/47450907/a49e04ef-eae3-4ad5-9cea-8a1d4f7a2e22">
Instance A received request and sent to instance B
<img width="1091" alt="instance A" src="https://github.com/jembi/openhim-core-js/assets/47450907/828719de-c943-47d5-8d94-cecc68460cad">
Instance B requests the end services that returns response
<img width="1091" alt="instance B" src="https://github.com/jembi/openhim-core-js/assets/47450907/664c1cf7-3efa-49cd-b0f9-0503612b2e38">

**Comment by rcrichton** [comment]
Thanks for these. Do you mind sharing what the response headers where in each case?

**Comment by reagan-meant** [comment]
Probably postman shows `br` as encoding

**Comment by rcrichton** [comment]
Yes, you are right. Could you please share the screenshots again with both the request and response header section expanded? That would make it easier for me to follow what might be going on. I think the OpenHIM A is saying it supports compression and  OpenHIM B then decided to use a compressed response but OpenHIM A it's not decompressing the response when sending it back to the client which doesn't support compression.

**Comment by rcrichton** [comment]
Some further findings. It seems OpenHIM support automatic decompression of `deflate` and `gzip` however we are getting `br` back in this example. So it's not decompressing the response.

https://github.com/jembi/openhim-core-js/blob/4ae2ac84b6a1ccf0561d7b7d5363413d221017f9/src/middleware/router.js#L592-L611

**Comment by reagan-meant** [comment]
<img width="1037" alt="resphead1" src="https://github.com/jembi/openhim-core-js/assets/47450907/ecb0fa9d-832f-4853-88bd-e7f25110eae3">
<img width="1037" alt="resphead2" src="https://github.com/jembi/openhim-core-js/assets/47450907/d550b6ae-0e48-4a55-aa2d-67f7bd34ac77">

**Comment by rcrichton** [comment]
It looks like in your original request you are supplying the header `accept-encoding: gzip, deflate, br` which means the client support decompression but it seems postman doesn't. Perhaps you need to adjust that header on your request to remove `br` from the values or remove the header entirely.

**Comment by reagan-meant** [comment]
@rcrichton adjusting the accept-encoding fixes the issue.
Thanks alot. cc @drizzentic
