### ISSUE TITLE
Support 'public' channels where request are not authenticated and authorised

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#146]

**Comment by debonair** [comment]
I am picking up this ticket and would like suggestions on how to tackle this @rcrichton @BMartinos @devcritter @bausmeier ? thoughts

**Comment by rcrichton** [comment]
Perhaps we could move make the authorisation middlewares not respond to the user as soon as the request in not authenticated, but rather allow the request though to the authorisation middleware, perhaps with a `this.authenticated = null`. Then the authorisation middleware can have final say over the request and respond appropriately. It can check if there are any public channel for a un-authenticated user, else respond 401.
