### ISSUE TITLE
Convert javascript generators to coffeescript

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#200]
Generator support has finally landed in coffee-script! - https://github.com/jashkenas/coffeescript/pull/3240

We should  refactor our generators to use coffee-script instead.

**Comment by devcritter** [comment]
It's been released!

**Comment by rcrichton** [comment]
Ok, I've made the issue an epic and broken down the work into these issues:

* https://github.com/jembi/openhim-core-js/issues/340
* https://github.com/jembi/openhim-core-js/issues/341
* https://github.com/jembi/openhim-core-js/issues/342
* https://github.com/jembi/openhim-core-js/issues/343
* https://github.com/jembi/openhim-core-js/issues/344
* https://github.com/jembi/openhim-core-js/issues/345
* https://github.com/jembi/openhim-core-js/issues/346
* https://github.com/jembi/openhim-core-js/issues/347
* https://github.com/jembi/openhim-core-js/issues/348
* https://github.com/jembi/openhim-core-js/issues/349
* https://github.com/jembi/openhim-core-js/issues/350
* https://github.com/jembi/openhim-core-js/issues/350
* https://github.com/jembi/openhim-core-js/issues/351
* https://github.com/jembi/openhim-core-js/issues/352
