### ISSUE TITLE
Async non-primary routes

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#209]
Currently we wait for all routes to respond before sending a response (from the primary) back to the client. Should we rather implement the non-primary routes asynchronously and respond to the client as soon as we receive the response from the primary? Or perhaps have a flag on a route to mark it as async?

This *should* be trivial to implement in the router by simply not adding a [promise](https://github.com/jembi/openhim-core-js/blob/master/src/middleware/router.coffee#L67) for any async roots, however this does make persistence a little trickier.

cc @armageddon

**Comment by debonair** [comment]
closed by #491
