### ISSUE TITLE
Investigate TCP channel issues

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#315]
See email below from Justin:
> I am running a seed script which fires off random ADT_A01 messages (random names, dob, etc.) in parallel (8 threads on two machines). When I run this against the CR directly everything works, however when I do this via a passthrough on the HIM it works for a few minutes and then stops. On the HIM’s log I see this:
 
> info: Routing mllp request
info: Opened mllp connection to 142.222.45.50:2100
info: Received response end character
info: Storing response for transaction: 54a6f0a13c545e324f4c5b68
info: sending counts to statsd for ohie-him.marc-hi.ca.Development.54a5993ca6bbc665396b8db4
info: sending durations to statsd for ohie-him.marc-hi.ca.Development.54a5993ca6bbc665396b8db4
info: Storing visualizer events for transaction: 54a6f0a13c545e324f4c5b68
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:742:11)
    at TCP.onread (net.js:535:26)

It could be an issue with the TCP server sockets not closing properly.

**Comment by devcritter** [comment]
This could be related to #272

**Comment by bausmeier** [comment]
Closed in https://github.com/jembi/openhim-core-js/commit/cd34fd45b3ecf0b2457cae864f8d49707db3b62e
