### ISSUE TITLE
Moment depracation warning

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#316]
Received the following message when running a transaction:
> info: The request, '/xdsregistry' is authorised to access XDS.b Repository
info: Storing request metadata for inbound transaction
info: Routing http(s) request
info: Storing response for transaction: 54aa5167c2a61537646309bf
info: sending counts to statsd for precise32.Development.54aa50d7c2a61537646309bb
info: sending durations to statsd for precise32.Development.54aa50d7c2a61537646309bb
info: Storing visualizer events for transaction: 54aa5167c2a61537646309bf
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

Just something to look into, definitely not a high priority at this stage.

**Comment by debonair** [comment]
OK cool. will fix this in my branch.

**Comment by devcritter** [comment]
Cool, thanks!
