### ISSUE TITLE
Dealing with delete channels

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#324]
A point that @BMartinos raised: how should we deal with deleted channels? In particular channels that have existing transactions?

Currently when a channel is deleted, the existing transactions will point to a non-existent channel. This means we can't display the channel names in the console or rerun those transactions (which is probably right). In addition these transactions won't show up on the dashboard (mongo aggregation) metrics.

So
1. Is this acceptable and we should leave it as is, or
2. should channels that have transactions linked against them be prevented from being deleted, or
3. have a flag that just marks them as deleted, or
4. should we store the channel name on a transaction in addition to the id, so that if deleted, we still have a reference?

**Comment by debonair** [comment]
I am in favour of marking a channel as deleted because so as to keep a reference to it. if there is need to completely delete a channel we could always put a "purge" method, that has the option of deleting the associated transactions as well.

**Comment by rcrichton** [comment]
Yeah, I agree. Maybe marking as deleted is best. I have also been thinking that we should be able to enable and disable channels, maybe this can be done using the same mechanism? We could have a flag with possible values of 'enabled', 'disabled' and 'deleted'?

**Comment by devcritter** [comment]
Yeah, agree such a flag would be useful.

**Comment by BMartinos** [comment]
I agree with the flag option. Think this will be a useful addition. So by default a channel is "enabled" and can route transactions, When "disabled", transactions cannot be routed and when "Deleted" transactions cannot be routed and the console entry is removed ( The channel still exists but its not displayed on the console )

**Comment by rcrichton** [comment]
Yeah, that's what I'm thinking.
