### ISSUE TITLE
Routes still send to an old endpoint when a channel's route has been updated

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#326]
I saw this occur with a MLLP and previously with a TCP route. It may only affect those types.

To recreate:
* setup a channel with a MLLP route
* send a transaction through the channel
* update the channel's route with a new host and port
* send a transaction through the channel
* notice that it still sends to the old endpoint in the logs
* restart the server
* send a transaction through the channel
* notice that the endpoint that the transaction is being sent to is now correct

**Comment by bausmeier** [comment]
The TCP servers (https://github.com/jembi/openhim-core-js/blob/787b2c9a571830eab9ed953f4cf075b877342494/src/tcpAdapter.coffee#L12) need to be restarted when their channels are updated. They get passed a channel when they are started (https://github.com/jembi/openhim-core-js/blob/787b2c9a571830eab9ed953f4cf075b877342494/src/tcpAdapter.coffee#L30) and when the channel gets updated in the database their channel gets out of sync.

**Comment by rcrichton** [comment]
Perhaps the TCP servers should query mongo for a channel on each request to them, as HTTP channels do. Else it would make this pretty confusing to the user.

**Comment by bausmeier** [comment]
That would make sense to me.
