### ISSUE TITLE
Vagrant: Time issues

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#329]
When firing up a new vagrant instance, its time is a little behind the actual current time. Most likely this would mean that the instance hasn't got NTP sync turned on. The time should be up to date, since it causes occasional login problems from console.

**Comment by devcritter** [comment]
In the meantime, the following post may be useful to anyone with time issues: http://jeremykendall.net/2014/10/06/forcing-an-ntp-update/

Although actually I just ran
```
sudo service ntp stop
sudo ntpd -gq
service ntp start
```
manually after startup to update the time to the current.

**Comment by devcritter** [comment]
Figured out what was going on and found a solution thanks to https://vilimpoc.org/blog/2014/02/09/better-time-synchronization-with-virtualbox-guest-additions/

Seems the date in the vagrant instance was drifting quite heavily. Within in a few minutes my instance was close to 30 seconds out. And the login problems came in because console stores the server diff time in session, so since the server clock was drifting, the stored diff time wasn't accurate any more.

Created a fix, just testing and will then push.

**Comment by psbrandt** [comment]
Wow, that's pretty crazy.
