### ISSUE TITLE
Visualizer not picking up orchestration events

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#334]
The visualizer seems to be struggling to pickup `orch-{name}` events

**Comment by devcritter** [comment]
So the issue isn't particularly related to the fact that it's an orchestration. It's related to the event timestamps: if a mediator is running on another server with a different time to core, then the orchestration timestamps will be out. This doesn't animate correctly since the events trigger at the wrong times (seconds or even minutes out of sync rather than milliseconds), and the timeout can kick in long before the event needs to be animated.

One solution could be to normalize the timestamps to the core time using the route start timestamp as a base.

**Comment by rcrichton** [comment]
I'd rather have us use timestamps with a time zone component so that this difference doesn't really matter.

**Comment by devcritter** [comment]
Yeah, agree on the time zone component.

A problem would still exist though if the mediator was on a server with the wrong time, even a couple seconds out would have some implications, since the timeouts might kick in before the events get a chance to animate. But maybe we shouldn't solve this in code, just ensure that all servers are NTP synced. One just needs to be aware that this could be an issue.

**Comment by carlsbox** [comment]
It does seem like a risk that we should put on the backlog to get addressed
in a future sprint.

Carl Fourie
---
*Assistant Director of Programs, Jembi Health Systems |  SOUTH AFRICA*
*Mobile: +27 71 540 4477 | Office: +27 21 701 0939 | Skype: carl.fourie17*
*E-mail: *carl.fourie@jembi.org
