### ISSUE TITLE
SSL handshake failed error with basic auth

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#335]
With only basic auth enabled (and mutual tls false), the server still seemed to require the client to authenticate with a certificate. The following was the output from curl
```
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
```

**Comment by devcritter** [comment]
Found the trigger for this: I have a bad habit due to a long-ago issue of adding `-k3` as a flag when testing the HIM with curl; -3 being the command for sslv3. It works fine without the 3.

Not sure why this flag is causing issues now and not before and what the correct behaviour should be. But happy to close this issue - we shouldn't be using v3 anyway! If it's an issue for anyone we can open a new ticket for SSLv3 support.

**Comment by carlsbox** [comment]
What version of SSL were we needing to use for mHERO @Ryan?

Carl Fourie
---
*Assistant Director of Programs, Jembi Health Systems |  SOUTH AFRICA*
*Mobile: +27 71 540 4477 | Office: +27 21 701 0939 | Skype: carl.fourie17*
*E-mail: *carl.fourie@jembi.org

**Comment by rcrichton** [comment]
I believe SSLv3 has been deemed insecure so node removed support for it. This may be the cause. We should be using TLSv1 and up only.

@carlsbox they didn't require a specific version but they also should be using TLSv1 and above.

See http://blog.nodejs.org/2014/10/23/node-v0-10-33-stable/ and http://en.wikipedia.org/wiki/POODLE

**Comment by litlfred** [comment]
Do you need me to do anything?

**Comment by devcritter** [comment]
Thanks @rcrichton 

@litlfred I'm pretty sure most clients wouldn't be using v3 unless explicitly enabled so everything should be fine. But if you want to be sure, you should just be able to upgrade to the latest node.
