### ISSUE TITLE
SyntaxError: Unexpected token *  in lib/koaMiddleware.js:49

### ISSUE THREAD

**Issue by allyshaban5** [jembi/openhim-core-js#353]
Hi,
I followed all the instructions of installing the openhim-core-js and everything went well. But when i run either npm test or grunt test or node --harmony lib/server.js i get the error as attached in the screenshot. Any help please.
![node](https://cloud.githubusercontent.com/assets/7733830/6017296/95613a18-ab9d-11e4-99e0-7bebb78c1deb.png)
![test](https://cloud.githubusercontent.com/assets/7733830/6017301/9b19ede2-ab9d-11e4-9bac-131254b8d89f.png)

**Comment by debonair** [comment]
Hi @allyshaban5  what version of nodejs are you running? please make sure its 0.11.9 or greater

**Comment by bausmeier** [comment]
I'm not sure what could be causing that other than using the wrong version
of node. The only thing I can suggest is running `node --version` to double
check that you are using the correct binary.

**Comment by allyshaban5** [comment]
I crosschecked the version and found it was still 0.10,i have upgraded it with npm and now its 0.11. But im still getting the error related to bcrypt. I tried to check on the node_modules directory for bcrypt and i didnt find it,i tried to run sudo npm install bcrypt and even npm install i get these errors

npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-59-generic-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "."
npm ERR! cwd /home/intrahealth/openhim-core-js-master
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE

**Comment by debonair** [comment]
try this 
sudo npm install -g n
sudo n latest
rm -rf node_modules
npm install

**Comment by rcrichton** [comment]
Trying to run this a node version lower than 0.11 causes this. I hope the above solved you problem.
