### ISSUE TITLE
Enable the OpenHIM to act as a CA

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#354]
The OpenHIM should be able to act as a CA. This mean that we should be able to generate certificates for clients on the fly. Also, the OpenHIM should allow the admin to generate a self-signed certificate for the OpenHIM server instance itself. This certificate should have the ability to sign other certificates. This mean that is must have the basicConstrainsts extension cA flag set to true (http://tools.ietf.org/html/rfc5280#section-4.2.1.9). This can cause problem as the there is no known module to do this in node land. Two possible options are:

* Use a openssl wrapper: https://www.npmjs.com/package/openssl-wrapper
* Modify pem to support this: https://www.npmjs.com/package/pem

Also, we would need a way to check that a certificate that a user uploads as the HIM server cert support signing certificates. If it does not we should disable the ability to generate client certificates.

**Comment by debonair** [comment]
@rcrichton What should the form on the console side look like? I have pushed an initial version for you to take a look. I want to know what you expect to happen after user fills in the form, ie what the API should return as a result.

Other questions:

1. Should I save the result to mongo
2. what files should I return the certificate for the user to download

**Comment by rcrichton** [comment]
Hey @debonair, the UI should allow the user to generate a certificate for a client (which is then added to the trusted certs list). They should be able to generate a certificate for the OpenHIM server itself. I'd guess you need buttons to initiate these actions then a form to capture the certificate details (common name, organisation, organisation unit etc. and the validity period). I think the API should just return 201 if the creation of the cert was successful. For generated client certs we should allow the user to download the cert and key, but I think this should only be allowed directly after generating the cert to prevent us from having to store the key for security reasons.

@devcritter @bausmeier thoughts?

**Comment by devcritter** [comment]
Should we rather use CSR's to sign client certificates, rather than generating the private key ourselves? Not that I'm a PKI expert at all, but it appears to be the standard way for CAs to operate. Of course we could still have functionality to generate the certificates/keys, it would certainly be useful, but currently we would exclude any clients that want to generate their own certs/keys and have those signed by the HIM.

**Comment by rcrichton** [comment]
I think that our first goal should be to make this as easy as possible for people setting up an OpenHIM instance. Generating CSRs isn't that straight forward if you are new to it. So I think we should do everything via the UI. That said, I agree, CSRs are the 'better' way to do this. Perhaps we can add support for this as well. I think we could create a new feature request for this so that we don't add too much complexity into this issue.

**Comment by devcritter** [comment]
Cool, sounds good.
