### ISSUE TITLE
/usr/local/lib/node_modules/openhim-core/node_modules/forever-monitor/node_modules/watch/main.js:73

### ISSUE THREAD

**Issue by allyshaban5** [jembi/openhim-core-js#355]
Hi,
I get this error when executing openhim-core.
Any idea please.
template@il:~/openhim-core-js$ openhim-core 
/usr/local/lib/node_modules/openhim-core/node_modules/forever-monitor/node_modules/watch/main.js:73
    if (err) throw err;
                   ^
Error: ENOENT, stat '/usr/local/lib/node_modules/openhim-core/lib'
    at Error (native)

**Comment by rcrichton** [comment]
Hi, I haven't seen this before. How did you install the openhim? What operating system are you using?

**Comment by rcrichton** [comment]
Also, does this folder exist? Is there anything inside it? `/usr/local/lib/node_modules/openhim-core/lib`

**Comment by allyshaban5** [comment]
I used the sinatllation instructions in https://github.com/jembi/openhim-core-js/ but i didnt use either Vagrant or puppet to install. I'm running it in ubuntu 14.04.The folder /usr/local/lib/node_modules/openhim-core/lib does not exist,and when i try to delete /usr/local/lib/node_modules and rerun npm install -g .,still the lib folder misses. when i try to mkdir the lib folder,it complains that some files are missing on it.
But this command does not give any error "NODE_ENV=production node --harmony lib/server.js"

**Comment by rcrichton** [comment]
The npm install command should build the openhim-core source files and place them in the lib folder. Do you get any errors when you with that npm install. Could you try running the command as follows and see if that makes a difference: `npm install . -g` Also, could you show us the output of the npm install?

**Comment by allyshaban5** [comment]
The command npm install . -g is of help. I can now start the open him server by just openhim-core.
Thnx.
