### ISSUE TITLE
update Transaction Schema to include custom metrics and orchestration groups

### ISSUE THREAD

**Issue by debonair** [jembi/openhim-core-js#363]
@devcritter thoughts? about how to represent orchestration groups

**Comment by devcritter** [comment]
Right, so following from the conversation from yesterday...
Just to summarize the context for everyone: Currently the orchestrations are just straightforward array in the schema, but it would great if there were a way to group orchestrations. For example if a mediator calls a mediator, it would be useful to group the second mediator's orchestrations together, or if there's a specific sub workflow, e.g. enrich patient identifiers, these could be grouped together. This is useful for namespacing the metrics as well as in general for display on the console.

@debonair @bausmeier does that about summarize it?

We could allow for sub documents in the model (orchestrations in orchestrations) but that makes it a little more unwieldy to work with. Another approach could be something like:
```
"orchestrations": [
  {
    "name": "addEvent"
    "group": "dhis"
    "request" ...
    "response" ...
  }
]
```
So here the `addEvent` would be namespaced under `dhis`. Or maybe it also needs a parent field to indicate that the orchestration is a child of another orchestration.

**Comment by debonair** [comment]
Yes I think that pretty much sums it up. its a really small change. The other part to this is to modify the mongoose Transaction schema to accomodate these changes as well as the custom metrics that I added.

**Comment by rcrichton** [comment]
I'l need to think on it a bit, but right now I think @devcritter's suggestion of adding a `group` property would be all we need.

**Comment by debonair** [comment]
Are we also adding the parent orchestration name to this schema?

**Comment by devcritter** [comment]
Maybe we should just keep it simple initially and just have `group`? You can then group according a parent. What do you guys think?

**Comment by rcrichton** [comment]
Yeah I agree, keeping it simple and just having `group` sounds good to me.
