### ISSUE TITLE
Enable the OpenHIM to act as an ATNA audit reposiotry

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#372]
This epic consists of:
* https://github.com/jembi/openhim-core-js/issues/373
* https://github.com/jembi/openhim-core-js/issues/374
* https://github.com/jembi/openhim-core-js/issues/375
* https://github.com/jembi/openhim-core-js/issues/376

**Comment by devcritter** [comment]
All subtasks closed.
