### ISSUE TITLE
Make bcrypt module optional (or even drop)?

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#387]
The bcrypt module is pretty heavy dependency. It's a native module so you always need a C++ compiler on your system (please correct me if I'm wrong! but that's what it [looks](https://github.com/ncb000gt/node.bcrypt.js/tree/master/src) like to me). In Windows in particular it's pretty rough since you need  something like Visual Studio, making it very difficult to install the HIM in a windows server environment.

We already dropped support for bcrypt in the Console (https://github.com/jembi/openhim-console/commit/38f053922cb8bfa20b336c8b1590e5c4d9a0b5bf), so it's already an API level feature only anyway.

Therefore should we:
1. make bcrypt optional having a runtime check like http://stackoverflow.com/questions/15302618/node-js-check-if-module-is-installed-without-actually-requiring-it (which may be a bit ugly, since an implementer would need to install it manually)
2. remove support for it completely

I vote for 2.

**Comment by bausmeier** [comment]
I think the best option would be to switch back to [the pure js version](https://github.com/dcodeIO/bcrypt.js). It's a drop in replacement, it's just slower. The mongodb module also has c++ bindings, but it automatically falls back to the js version if it needs to.

**Comment by devcritter** [comment]
Thanks @bausmeier. Alright that's a good suggestion. Yeah the problem is that with the current bcrypt module, it can't switch back to a js version.

Any objections from anyone if we proceed with this?

**Comment by rcrichton** [comment]
That works for me. Although removing it completely may be an option to. But, I'm happy with this solution.
