### ISSUE TITLE
manual install instructions missing some grunt modules

### ISSUE THREAD

**Issue by litlfred** [jembi/openhim-core-js#392]
grunt build gives:
>> Local Npm module "grunt-coffeelint" not found. Is it installed?
>> Local Npm module "grunt-contrib-coffee" not found. Is it installed?
>> Local Npm module "grunt-contrib-clean" not found. Is it installed?
>> Local Npm module "grunt-mocha-cli" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?

I think the solution is:
npm install grunt-coffeelint grunt-contrib-coffee grunt-contrib-clean grunt-mocha-cli grunt-contrib-watch

**Comment by rcrichton** [comment]
I think manually installing these modules caused your other problem. These should be installed when you do a `npm install` as they are listed in the package.json file under dev-dependancies. Maybe you should remove you node_modules folder and try an `npm install` again

**Comment by litlfred** [comment]
My bad.  That worked.  Thanks
