### ISSUE TITLE
node 0.12 error on grunt build

### ISSUE THREAD

**Issue by litlfred** [jembi/openhim-core-js#393]
Not sure if this is just a configuration issue on my end, but I was trying to build with node 0.12 and I got the following.  Any hints would be appreciated.

>> Running "coffee:compile" (coffee) task
>> src/api/authentication.coffee:27:10: error: reserved word "yield"
>>   user = yield User.findOne(email: email).exec()
>>          ^
>> In file: src/api/authentication.coffee
>> On line: 26
>>   user = yield User.findOne(email: email).exec()
>>          ^
Warning: CoffeeScript failed to compile. Use --force to continue.

**Comment by rcrichton** [comment]
Could you try do an 'npm update' first. You may need the latest
coffeescript.

Cheers,
Ryan

**Comment by litlfred** [comment]
It was a clean install, but I did that anyways.  No luck.

I also checked with 0.11.16 and got the same error. :-(

**Comment by litlfred** [comment]
Is it related to having strict mode turned on?
  http://stackoverflow.com/questions/28414973/unexpected-strict-mode-reserved-word-yield-node-v0-11-harmony-es6

**Comment by rcrichton** [comment]
It seems to build fine for me. What command are you running here? I'm pretty sure this is because somewhere one of the tools is using an older version of coffeescript. Are you trying this with the latest in master?

**Comment by devcritter** [comment]
I just ran into this same issue as well. But all I did though was run `npm install` and then after that it worked fine.

**Comment by litlfred** [comment]
Yep, that worked for me as well.
