### ISSUE TITLE
Error setting server key with CA signed PEM

### ISSUE THREAD

**Issue by justin-fyfe** [jembi/openhim-core-js#417]
When uploading a cert/key signed by a CA with a passphrase on the private key the console shows a key/certificate mis-match. 

Steps to reproduce:
1. Generate a private key with passphrase, CSR, and get a signed certificate.
2. In OpenHIM Console -> Certificates upload the cert pem and key pem
3. The OpenHIM Console will show a key mis-match error

Suggested fix:
Allow the configuration of a passphrase for the server's private key either as a config option or in the UI.

Cheers
-Justin

**Comment by rcrichton** [comment]
Thanks Justin, good idea.

**Comment by justin-fyfe** [comment]
NB: This also affects the client side requests that the HIM makes to other behind the HIM services. It can be fixed by adding the passphrase option to the connection.
