### ISSUE TITLE
Use certificate thumbprint or serial number instead of CN

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#419]
When authenticating clients, it may more secure to validate the cert on the thumbprint (/fingerprint) or the certificate serial number instead of the CN (https://github.com/jembi/openhim-core-js/blob/master/src/middleware/tlsAuthentication.coffee#L64).

**Comment by rcrichton** [comment]
This has proven to be an issue, see comments in #464, and should be addressed asap.

Basically if there is any self-signed certificate that we trust it would be possible for that client to sign a new cert using their own cert and key that has a different commonName. Thus, they can access other client's channels.

From discussion with Brett we think the best way to resolve this would be to link a client to a unique attribute of the certificate (thumbprint/fingerprint/modulus whichever is best and can't be faked). Then change the UI to allow the user to choose a certificate to link to a client (via a drop down box or similar).

The certificate path walking from issue #418 will also need to change.

@bausmeier anything I've missed?
