### ISSUE TITLE
Use ensureIndex rather than createIndex in visualizer?

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#428]
From looking at the flame graph it seems we spend some time creatIndex. It seems this is coming from https://github.com/jembi/openhim-core-js/blob/master/src/middleware/visualizer.coffee#L141

Perhaps use ensureIndex instead? http://mongodb.github.io/node-mongodb-native/markdown-docs/indexes.html#ensure-indexes-with-ensureindex

**Comment by devcritter** [comment]
Aah oops, sorry my bad. Yeah `ensureIndex` is definitely preferable.
