### ISSUE TITLE
Tasks: multiple transaction running strategies

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#438]
Currently when a task runs, the worker thread will move on to the next item in the task as soon as the request for the previous item has been fired off (i.e. it doesn't wait for a transaction to finish first). This is definitely a good strategy as it keeps the worker busy, but it can quickly overwhelm a target server with too many transactions.

For certain contexts it would be better to run transactions one by one, waiting for each to finish before moving on to the next.

Taking into account that sometimes you do want to move through a task faster than one at a time, should we introduce a configurable running strategy? Perhaps when submitting a task, along with the transaction ids, maybe you could specify a concurrency level for that task?

**Comment by rcrichton** [comment]
Perhaps we should have an option of running these is batches? with the options of something like:

Batch size:
* one at a time
* 2
* 4
* 8
* 16
* 32
* 64

**Comment by devcritter** [comment]
Yeah, sounds good
