### ISSUE TITLE
Channel Route URL Paramaters bug

### ISSUE THREAD

**Issue by BMartinos** [jembi/openhim-core-js#444]
When channel routes (non primary) have attached parameters they do not seem to get split up into 'path' and 'querystring' values. 

Screenshots below:
Channel Route Setup:
![channel-routes](https://cloud.githubusercontent.com/assets/7311421/6706359/5e544364-cd65-11e4-86af-3ab6a7d7e435.png)

Transaction Details View (Routes)
![transaction-route](https://cloud.githubusercontent.com/assets/7311421/6706364/65e29cde-cd65-11e4-8c9f-8f12734c156b.png)

**Comment by BMartinos** [comment]
Not really sure if this is a bug or if i have just tried it in the incorrect way. 

When the original request has query parameters then it gets saved for the route parameters as well. When the query parameters are added to the route path/pathTransform it does not

**Comment by rcrichton** [comment]
Hey @BMartinos, I'm not sure I completely understand but I don't think we should add parameter to the path column in general. Those will likely only be sent by client when they are making the request, I don't think we need to be able to set them statically in routes.

**Comment by BMartinos** [comment]
ok cool i must have then tried it in the incorrect way expecting a diff result but they way you explain it makes sense. This is then not a bug but incorrect use of the query params. 

Ill close this issue as it is not a bug
