### ISSUE TITLE
Unhandled ssl error

### ISSUE THREAD

**Issue by bausmeier** [jembi/openhim-core-js#460]
There seems to be a missing error handler on one of the tls sockets which causes the HIM to crash occasionally. This error should be handled so that only the connection fails, not the whole HIM.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: 140542554728256:error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1026:

    at Error (native)
```

**Comment by BMartinos** [comment]
Some extra logging below:
---------------------------------------------------
praekelt is authenticated.
info: The request, '/ws/rest/v1/subscription' is authorised to access Subscription
info: Storing request metadata for inbound transaction
info: Routing http(s) request
info: Routing http(s) request
info: Storing response for transaction: 550fe63011c777002a9dcd9f
info: sending counts to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4e0
info: sending durations to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4e0
info: Storing response for transaction: 550fe63011c777002a9dcda0
info: sending counts to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4dd
info: sending durations to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4dd
info: Storing visualizer events for transaction: 550fe63011c777002a9dcd9f
info: Storing visualizer events for transaction: 550fe63011c777002a9dcda0
info: praekelt is authenticated.
info: The request, '/ws/rest/v1/facilityCheck' is authorised to access Facility Check
info: Storing request metadata for inbound transaction
info: Routing http(s) request
info: Routing http(s) request
info: Storing response for transaction: 550fe63d11c777002a9dcdb5
info: sending counts to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4db
info: sending durations to statsd for momconnect-him.Production.550c2c5febaab96a71b3d4db
info: Storing visualizer events for transaction: 550fe63d11c777002a9dcdb5
info: Stopped rerun task processor
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: 140089564587840:error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1026:

    at Error (native)
Forever detected script exited with code 1
Forever restarting script for 1 time
info: Starting OpenHIM server on localhost...
info: Started rerun task processor
info: HTTP listening on port 5002
info: Transaction Rerun HTTP listening on port 7786
info: HTTP receiver for Socket adapter listening on port 7787
info: Polling port listening on port 7788
info: API HTTPS listening on port 8081
info: HTTPS listening on port 5003
info: OpenHIM server started: Mon Mar 23 2015 10:09:04 GMT+0000 (UTC)
info: Started agenda job scheduler
info: praekelt is authenticated.
info: praekelt is authenticated.
---------------------------------------------------------

**Comment by BMartinos** [comment]
Something weird that was noticed is the 'Stopped rerun task processor' that gets logged before the error. This has happened a few times when this error is noticed in the logs. What could be calling this stop procedure?

**Comment by BMartinos** [comment]
Based on the logs it showed that this error still happens a few times during the day ( random times ). Last logged ssl error was roughly around 12:10pm on 9th April

**Comment by rcrichton** [comment]
That is weird, it could be that as the server is crashing we are calling stop and that is causing it to print that out. https://github.com/jembi/openhim-core-js/blob/master/src/server.coffee#L568-L578

Then it wouldn't really point to a reason why the we are getting the ssl error though.
