### ISSUE TITLE
Daily/Weekly reports not being sent

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#466]

**Comment by debonair** [comment]
There is a  need to update agenda to the latest version currently on version on 0.6.26
the latest is 0.6.28. There have been some bug fixes since then.

**Comment by rcrichton** [comment]
Is this causing the issue though? There are probably only minor bug fixes in the new release.

**Comment by debonair** [comment]
The issue we found was that the jobs were locked. @bausmeier has released the locks, we will see if we get a daily report tomorrow. I still guess it is prudent to update to the latest agenda if we can. I could not figure out why the jobs were locked in the first place. I am looking into that

**Comment by rcrichton** [comment]
@debonair I'm still not getting the reports. Any ideas?

**Comment by debonair** [comment]
Check if the job is locked in the the agenda collection

**Comment by rcrichton** [comment]
Have you been able to get any reports out of the system?
