### ISSUE TITLE
MLLP requests taking 10s to respond from OpenEMPI

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#468]

**Comment by debonair** [comment]
@rcrichton Please add a clearer description on how to replicate this bug.

**Comment by rcrichton** [comment]
Hey @debonair, the OpenHIE team is experiencing a problem where any PIX/PDQ message being sent to OpenEMPI takes almost exactly 10s to respond. This points to the same issue we had before the MLLP route option where the HIM was only responding when the socket timed out.

To reproduce:
1.  Configure an mllp route to OpenEMPI
2.  Send a PIX/PDQ message through the HIM to OpenEMPI
3.  Observe that is takes 10s to process where it should be <1s

**Comment by debonair** [comment]
@rcrichton I am testing with the latest version of OpenEMPI (i.e verson 3.0.0)To and cannot replicate this issue, will downgrade to a previous version and see. Do you have any idea what version they were using?

**Comment by rcrichton** [comment]
Hey @debonair, I'm not sure which version they are using. I'l loop you in on the email thread and we can find out more.

**Comment by debonair** [comment]
OK cool, also ask the version of the OpenHIM they are using, whether its a tagged release or the latest master.

**Comment by debonair** [comment]
No code was written to fix this issue,

**Comment by devcritter** [comment]
Hey @debonair, so what was the issue?

**Comment by debonair** [comment]
One of the routes was down( a non primary route), so it was waiting for 10 seconds for the connection to time out, then it would respond to the client
