### ISSUE TITLE
Fix daily and weekly reports

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#483]
Daily and weekly reports don't seen to be working. I'm done a bit of digging into this, but haven't got to the bottom of it. Here is what I found:

* It looks like a channel is associated with only one user, wouldn't this prevent reports being produced for multiple users? https://github.com/jembi/openhim-core-js/blob/master/src/reports.coffee#L38
* In my local testing it gets stuck here: https://github.com/jembi/openhim-core-js/blob/master/src/reports.coffee#L58 it seems that not all promises are being resolved. I see that no error condition are being handled, perhaps `fetchChannelReport()` isn't calling the callback on an error condition?

@debonair please add your findings here.

**Comment by debonair** [comment]
The issue seems to occur when there is more than one channel to report on, The innerPromise array of promises is not getting resolved
