### ISSUE TITLE
Prettyify the daily and weekly reports

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#492]
Carl had the following to say: "Like getting these reports :) we should chat about the formatting maybe? Could we create a ticket that looks at pretty'fying these a bit? Maybe some HTML in the file and stuff like removing the word "transactions" as well as putting units in the table headings (Ave response time??) and formatting to maybe 2 decimal points?"

I think adding some inline css to improve the colour, font and general look of these would also be good. Perhaps something to match our new console look.

**Comment by debonair** [comment]
closed by #503
