### ISSUE TITLE
Add server to request model

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#497]
We currently only capture the `path` for a [request](https://github.com/jembi/openhim-core-js/blob/d6bea4c94dbcfc4b84ae625160c6d33f1fb65c35/src/model/transactions.coffee#L7-L13). It would be useful to capture the server information as well: specifically the **host** and **port** that the request got sent to.

This would be good for orchestrations as the information isn't captured at all (for the main request this information is implicit in the channel route).

**Comment by rcrichton** [comment]
Good idea, so specifically you are talking about when sending request to routes? I'm not quite sure where we can store this. Currently we don't store the don't actually store the request as it was send to the primary route either I don't think.

**Comment by devcritter** [comment]
Just took a look at the db and I see we do have a request object on secondary routes. I think it might be enough just to add the fields to the request definition? (https://github.com/jembi/openhim-core-js/blob/d6bea4c94dbcfc4b84ae625160c6d33f1fb65c35/src/model/transactions.coffee#L7-L13)

I think from there only the router would need updating.

**Comment by rcrichton** [comment]
Perhaps each route and the transaction itself (for primary routes) should have a `source` and `destination` property that stores information such as host and port.
