### ISSUE TITLE
Bug: Core crashing

### ISSUE THREAD

**Issue by BMartinos** [jembi/openhim-core-js#500]
I found the below bug in core when sending through a transaction: Core crashes when it doesnt find response.timestamp. Could potential be due to a mediator error being used but core error should be handled
![screenshot from 2015-05-25 16 23 18](https://cloud.githubusercontent.com/assets/7311421/7798486/bc9e8aea-02fa-11e5-9e8c-d4615d641c97.png)

**Comment by debonair** [comment]
This occurs when the orchestration response timestamp is not set.
