### ISSUE TITLE
Update API docs with complete filter list for transactions

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#515]
Update the docs [here](https://github.com/jembi/openhim-core-js/wiki/RESTful-API-reference) for the GET /transactions endpoint listing all the query parameter filters that are available.

**Comment by devcritter** [comment]
Took a stab at this. Will close the ticket but please add to the doc if I missed anything. @BMartinos you might be the best placed to take a look if you've got some space sometime?

That filters object a bit hectic for an API. I wonder if we shouldn't try think of a way to improve that a bit?

**Comment by BMartinos** [comment]
@devcritter The content in the wiki looks good to me. I agree the Filters object is probably a bit hectic for the API but im not too sure how this can be simplified without changing the GET into a POST or by removing some of the filters options. Maybe a brainstorming session might bring up better ideas or simplified way of doing this

**Comment by rcrichton** [comment]
Thanks for the edits @devcritter, looks good. I agree the filter object could be simpler. We should think about changing this. It would likely mean a major version bump for the OpenHIM but that's ok I think.

Also, I've been wondering if we should move all the docs into the actual repository along side the code. That will give us a way to version the docs along side the code and encourage everyone to add to the API docs along with code changes. What do you guys think?

**Comment by devcritter** [comment]
Ok cool. Yeah I think a major version bump is okay too. Might be good to get over that version 2 hurdle sooner rather than later :)

As discussed; keeping the docs in the repo is a great idea! I went ahead and created an issue: #517
