### ISSUE TITLE
The visualizer test seem to periodically fail.

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#562]
There must be some sort of race condition as the visualiser test occasionally fail with:

```
  1) Visualizer Integration Tests should set the transaction status as a string:

      Uncaught AssertionError: expected 3 to be 6
      + expected - actual

      -3
      +6
      
      at Test.<anonymous> (test/integration/visualizerTests.coffee:166:44)
      at endReadableNT (_stream_readable.js:893:12)
```

**Comment by devcritter** [comment]
Oh... I think I know why it's happening - we're saving the events using setTimeout: https://github.com/jembi/openhim-core-js/blob/master/src/middleware/events.coffee#L154

This just allows the response to the client to happen without needing to wait for the events. Oops, obviously the tests would be unreliable :) forgot about this when I wrote these!
