### ISSUE TITLE
Disabled channels should not appear in reports

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#599]

**Comment by hnnesv** [comment]
Thinking about this a bit - I'm not sure if this would be the best behaviour. A report is about "what happened", so it shouldn't matter if a channel is enabled or disabled, it should appear in the report if there are transactions during the report's period.

Perhaps we should only have a channel NOT appear if it's both disabled AND has zero transactions?
(and enabled channels appear regardless of the number of transactions...)

**Comment by rcrichton** [comment]
Cool, I agree. This is the situation that I want to avoid:

![momconnect-report](https://cloud.githubusercontent.com/assets/266576/12915862/b328f8fc-cf36-11e5-8696-4cf2af82492a.png)

So perhaps a zero value and the fact that the channel is disabled would be best filter.
