### ISSUE TITLE
We should trust common root CAs when authenticating clients

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#655]
Right now we poison the CA list of our https server with only the certificates that we trust from our keystore. This mean that TLS verification will fail for any certificate that we don't have the full certificate chain (up to the the root CA) for. It seems it is common for root CAs not to give out their root certificates and rather rely on intermediate certificates to prevent them from having to re-issue all certificates if they happen to be compromised.

Thus, it is impossible to authenticate with the OpenHIM with a certificate signed by one of the CAs where the root CA isn't available. This means that for the most part only self signed chains can be used.

To solve this we could add the common root CAs back to the OpenHIM's https server using something like https://github.com/coolaj86/node-ssl-root-cas#rootcas

**Comment by rcrichton** [comment]
cc/ @hnnesv @bausmeier - guys is this logic sound and does this seems like a good idea?

**Comment by bausmeier** [comment]
Makes sense to me @rcrichton.

**Comment by hnnesv** [comment]
Does the https server's CA list apply though with [rejectUnauthorized](https://github.com/jembi/openhim-core-js/blob/76fa8f4bfe733af749603eb8b21e9016ee2cbe52/src/middleware/tlsAuthentication.coffee#L64) set as false?

**Comment by rcrichton** [comment]
It does because we use the https servers authorized property to determine if the client is authenticated: https://github.com/jembi/openhim-core-js/blob/master/src/middleware/tlsAuthentication.coffee#L132

**Comment by rcrichton** [comment]
I have tested the referenced PR with a DATIM certificate and it only works if I add in the CAs.

**Comment by hnnesv** [comment]
Aah ok cool thanks - it's making more sense to me now
