### ISSUE TITLE
Testing loadDefaultChannels() issue

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#727]
Occasionally we get this error during testing:

```
  1) API Integration Tests Mediators REST API testing *loadDefaultChannels() should add all channels in the defaultChannelConfig property:
      Uncaught AssertionError: expected 'Save Encounter 2' to be 'Save Encounter 1'
      + expected - actual
      -Save Encounter 2
      +Save Encounter 1
      
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at Query.<anonymous> (test/integration/mediatorAPITests.coffee:1099:46)
      at node_modules/mongoose/node_modules/kareem/index.js:177:19
      at node_modules/mongoose/node_modules/kareem/index.js:109:16
Warning:  Use --force to continue.
Aborted due to warnings.
```

**Comment by napiergit** [comment]
Cannot ensure [this order](https://github.com/jembi/openhim-core-js/blob/master/test/integration/mediatorAPITests.coffee#L1164-L1165), because they are fired off asynchronously [here](https://github.com/jembi/openhim-core-js/blob/master/src/api/mediators.coffee#L320)

**Comment by hnnesv** [comment]
Good catch. One approach to address these is to setup an array with the channel names and using [`containEql`](http://shouldjs.github.io/#assertion-containeql) to check if the exected values are present. E.g. [here](https://github.com/jembi/openhim-core-js/blob/master/test/unit/alertsTest.coffee#L403-L409)

**Comment by napiergit** [comment]
Thanks, was wondering what the best approach would be.
