### ISSUE TITLE
Gruntfile.js Missing

### ISSUE THREAD

**Issue by austinsdoe** [jembi/openhim-core-js#935]
I trying to evaluate Openhim but it seems the Gruntfile that is suppose to be in the project home's directory is missing.  Use both Vagrant and the manual install.  Any way forward?

**Comment by MattyJ007** [comment]
This project no longer uses grunt.

For a quick setup guide please see the following tutorial:
https://www.youtube.com/watch?v=F0bTS3qJlG0
